### ISSUE TITLE
index.js line 17 giving errors after doing cov invite

### ISSUE THREAD

**Issue by JssPlayZ** [theStonedSage/covid-discord-bot#3]
com[parsed.command](message,parsed.arguments)
This line have errors please solve that ASAP
Btw very nice video and editing

**Comment by theStonedSage** [comment]
hey , line 17 responds to commands defined in command.js ( line 344 onwards ). I have not made an invite function/command so its showing an error. you can go through the following link and create the invite command yourself , its pretty easy.

https://discordjs.guide/preparations/adding-your-bot-to-servers.html#bot-invite-links

and thanx for the feedback , I'll soon be releasing a new tutorial series on making fb games from scratch so do check it out.
